"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  Users,
  Calendar,
  Clock,
  Plus,
  MessageSquare,
  ChevronRight,
  RefreshCw,
  Settings,
  Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { OneOnOnePrep } from "@/components/meetings/one-on-one-prep";

interface Profile {
  id: string;
  full_name: string;
  avatar_url: string | null;
  title: string | null;
  email: string;
}

interface OneOnOneMeeting {
  id: string;
  title: string;
  meeting_day: string | null;
  meeting_time: string | null;
  duration_minutes: number;
  is_active: boolean;
  manager: Profile;
  direct: Profile;
}

interface CurrentUser {
  id: string;
  full_name: string;
  access_level: string;
}

export default function OneOnOnesPage() {
  const [meetings, setMeetings] = useState<OneOnOneMeeting[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentUser, setCurrentUser] = useState<CurrentUser | null>(null);
  const [selectedMeeting, setSelectedMeeting] = useState<OneOnOneMeeting | null>(null);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [directReports, setDirectReports] = useState<Profile[]>([]);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoGenerateResult, setAutoGenerateResult] = useState<{
    created: number;
    skipped: number;
    errors: string[];
  } | null>(null);

  // Create form state
  const [newMeetingDirectId, setNewMeetingDirectId] = useState("");
  const [newMeetingDay, setNewMeetingDay] = useState("");
  const [newMeetingTime, setNewMeetingTime] = useState("");
  const [creatingMeeting, setCreatingMeeting] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [meetingsRes, userRes] = await Promise.all([
        fetch("/api/one-on-ones"),
        fetch("/api/users/me"),
      ]);

      if (meetingsRes.ok) {
        const data = await meetingsRes.json();
        setMeetings(data);
      }

      if (userRes.ok) {
        const userData = await userRes.json();
        setCurrentUser(userData);

        // If user is a manager, fetch their direct reports
        const directsRes = await fetch(`/api/team?manager_id=${userData.id}`);
        if (directsRes.ok) {
          const directsData = await directsRes.json();
          setDirectReports(directsData);
        }
      }
    } catch (error) {
      console.error("Failed to fetch data:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateMeeting = async () => {
    if (!newMeetingDirectId || !currentUser) return;

    setCreatingMeeting(true);
    try {
      const response = await fetch("/api/one-on-ones", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          manager_id: currentUser.id,
          direct_id: newMeetingDirectId,
          meeting_day: newMeetingDay || null,
          meeting_time: newMeetingTime || null,
        }),
      });

      if (response.ok) {
        await fetchData();
        setShowCreateDialog(false);
        setNewMeetingDirectId("");
        setNewMeetingDay("");
        setNewMeetingTime("");
      }
    } catch (error) {
      console.error("Error creating meeting:", error);
    } finally {
      setCreatingMeeting(false);
    }
  };

  const handleAutoGenerate = async () => {
    setAutoGenerating(true);
    setAutoGenerateResult(null);
    try {
      const response = await fetch("/api/one-on-ones/auto-generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sync: true }),
      });

      if (response.ok) {
        const result = await response.json();
        setAutoGenerateResult(result);
        await fetchData();
      }
    } catch (error) {
      console.error("Error auto-generating meetings:", error);
    } finally {
      setAutoGenerating(false);
    }
  };

  const getInitials = (name: string) => {
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  };

  const formatDay = (day: string | null) => {
    if (!day) return null;
    return day.charAt(0).toUpperCase() + day.slice(1);
  };

  const formatTime = (time: string | null) => {
    if (!time) return null;
    const [hours, minutes] = time.split(":");
    const hour = parseInt(hours);
    const ampm = hour >= 12 ? "PM" : "AM";
    const hour12 = hour % 12 || 12;
    return `${hour12}:${minutes} ${ampm}`;
  };

  // Separate meetings into manager and direct views
  const asManagerMeetings = meetings.filter(
    (m) => currentUser && m.manager.id === currentUser.id
  );
  const asDirectMeetings = meetings.filter(
    (m) => currentUser && m.direct.id === currentUser.id
  );

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <Skeleton className="h-8 w-48" />
          <Skeleton className="h-10 w-32" />
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {[...Array(4)].map((_, i) => (
            <Card key={i}>
              <CardContent className="p-6">
                <div className="flex items-start gap-4">
                  <Skeleton className="h-12 w-12 rounded-full" />
                  <div className="space-y-2 flex-1">
                    <Skeleton className="h-5 w-32" />
                    <Skeleton className="h-4 w-24" />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  // If a meeting is selected, show the prep view
  if (selectedMeeting) {
    const isManager = currentUser?.id === selectedMeeting.manager.id;
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={() => setSelectedMeeting(null)}>
            <ChevronRight className="h-4 w-4 rotate-180 mr-2" />
            Back to 1:1s
          </Button>
        </div>
        <OneOnOnePrep meetingId={selectedMeeting.id} isManager={isManager} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Users className="h-6 w-6 text-indigo-600" />
            <h1 className="text-2xl font-semibold">My 1:1s</h1>
          </div>
          <p className="text-muted-foreground mt-1">
            {meetings.length} active 1:1 meeting{meetings.length !== 1 ? "s" : ""}
          </p>
        </div>
        <div className="flex gap-2">
          {currentUser?.access_level === "admin" && (
            <Button variant="outline" onClick={() => setShowAutoGenerateDialog(true)}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Auto-Generate
            </Button>
          )}
          {asManagerMeetings.length < directReports.length && (
            <Button onClick={() => setShowCreateDialog(true)}>
              <Plus className="h-4 w-4 mr-2" />
              New 1:1
            </Button>
          )}
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-full bg-indigo-100">
                <Users className="h-6 w-6 text-indigo-600" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">As Manager</p>
                <p className="text-2xl font-semibold">{asManagerMeetings.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-full bg-green-100">
                <MessageSquare className="h-6 w-6 text-green-600" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">As Direct Report</p>
                <p className="text-2xl font-semibold">{asDirectMeetings.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-full bg-purple-100">
                <Calendar className="h-6 w-6 text-purple-600" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Total 1:1s</p>
                <p className="text-2xl font-semibold">{meetings.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tabs for Manager/Direct views */}
      <Tabs defaultValue={asManagerMeetings.length > 0 ? "manager" : "direct"}>
        <TabsList>
          <TabsTrigger value="manager" className="gap-2">
            <Users className="h-4 w-4" />
            My Direct Reports ({asManagerMeetings.length})
          </TabsTrigger>
          <TabsTrigger value="direct" className="gap-2">
            <MessageSquare className="h-4 w-4" />
            With My Manager ({asDirectMeetings.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="manager" className="mt-6">
          {asManagerMeetings.length === 0 ? (
            <Card>
              <CardContent className="p-12 text-center">
                <Users className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium">No 1:1s with direct reports</h3>
                <p className="text-muted-foreground mb-4">
                  {directReports.length > 0
                    ? "Create 1:1 meetings with your direct reports"
                    : "You don't have any direct reports yet"}
                </p>
                {directReports.length > 0 && (
                  <Button onClick={() => setShowCreateDialog(true)}>
                    <Plus className="h-4 w-4 mr-2" />
                    Create 1:1
                  </Button>
                )}
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {asManagerMeetings.map((meeting) => (
                <Card
                  key={meeting.id}
                  className="cursor-pointer hover:shadow-md transition-shadow"
                  onClick={() => setSelectedMeeting(meeting)}
                >
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <Avatar className="h-12 w-12">
                        <AvatarImage src={meeting.direct.avatar_url || undefined} />
                        <AvatarFallback className="bg-indigo-100 text-indigo-700">
                          {getInitials(meeting.direct.full_name)}
                        </AvatarFallback>
                      </Avatar>
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium truncate">{meeting.direct.full_name}</h3>
                        <p className="text-sm text-muted-foreground truncate">
                          {meeting.direct.title || meeting.direct.email}
                        </p>
                        {(meeting.meeting_day || meeting.meeting_time) && (
                          <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground">
                            {meeting.meeting_day && (
                              <div className="flex items-center gap-1">
                                <Calendar className="h-3 w-3" />
                                <span>{formatDay(meeting.meeting_day)}</span>
                              </div>
                            )}
                            {meeting.meeting_time && (
                              <div className="flex items-center gap-1">
                                <Clock className="h-3 w-3" />
                                <span>{formatTime(meeting.meeting_time)}</span>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                      <ChevronRight className="h-5 w-5 text-muted-foreground" />
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="direct" className="mt-6">
          {asDirectMeetings.length === 0 ? (
            <Card>
              <CardContent className="p-12 text-center">
                <MessageSquare className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium">No 1:1 with your manager</h3>
                <p className="text-muted-foreground">
                  Your manager hasn&apos;t set up a 1:1 meeting yet
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {asDirectMeetings.map((meeting) => (
                <Card
                  key={meeting.id}
                  className="cursor-pointer hover:shadow-md transition-shadow"
                  onClick={() => setSelectedMeeting(meeting)}
                >
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <Avatar className="h-12 w-12">
                        <AvatarImage src={meeting.manager.avatar_url || undefined} />
                        <AvatarFallback className="bg-green-100 text-green-700">
                          {getInitials(meeting.manager.full_name)}
                        </AvatarFallback>
                      </Avatar>
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium truncate">{meeting.manager.full_name}</h3>
                        <p className="text-sm text-muted-foreground truncate">
                          {meeting.manager.title || meeting.manager.email}
                        </p>
                        {(meeting.meeting_day || meeting.meeting_time) && (
                          <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground">
                            {meeting.meeting_day && (
                              <div className="flex items-center gap-1">
                                <Calendar className="h-3 w-3" />
                                <span>{formatDay(meeting.meeting_day)}</span>
                              </div>
                            )}
                            {meeting.meeting_time && (
                              <div className="flex items-center gap-1">
                                <Clock className="h-3 w-3" />
                                <span>{formatTime(meeting.meeting_time)}</span>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                      <ChevronRight className="h-5 w-5 text-muted-foreground" />
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* Create 1:1 Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create 1:1 Meeting</DialogTitle>
            <DialogDescription>
              Set up a recurring 1:1 with one of your direct reports
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Direct Report</Label>
              <Select value={newMeetingDirectId} onValueChange={setNewMeetingDirectId}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a direct report" />
                </SelectTrigger>
                <SelectContent>
                  {directReports
                    .filter(
                      (dr) => !asManagerMeetings.some((m) => m.direct.id === dr.id)
                    )
                    .map((dr) => (
                      <SelectItem key={dr.id} value={dr.id}>
                        {dr.full_name}
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Meeting Day (optional)</Label>
                <Select value={newMeetingDay} onValueChange={setNewMeetingDay}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select day" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="monday">Monday</SelectItem>
                    <SelectItem value="tuesday">Tuesday</SelectItem>
                    <SelectItem value="wednesday">Wednesday</SelectItem>
                    <SelectItem value="thursday">Thursday</SelectItem>
                    <SelectItem value="friday">Friday</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Meeting Time (optional)</Label>
                <Input
                  type="time"
                  value={newMeetingTime}
                  onChange={(e) => setNewMeetingTime(e.target.value)}
                />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleCreateMeeting}
              disabled={!newMeetingDirectId || creatingMeeting}
            >
              {creatingMeeting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
              Create 1:1
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto-Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Auto-Generate 1:1 Meetings</DialogTitle>
            <DialogDescription>
              Automatically create 1:1 meetings based on the org structure (manager relationships).
              This will create meetings for any manager-direct pairs that don&apos;t already have one.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {autoGenerateResult ? (
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-green-600">
                  <Badge className="bg-green-100 text-green-800">
                    {autoGenerateResult.created} created
                  </Badge>
                  <Badge variant="outline">
                    {autoGenerateResult.skipped} skipped (already exist)
                  </Badge>
                </div>
                {autoGenerateResult.errors.length > 0 && (
                  <div className="text-sm text-red-600">
                    {autoGenerateResult.errors.map((err, i) => (
                      <p key={i}>{err}</p>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                Click &quot;Generate&quot; to create 1:1 meetings for all manager-direct relationships
                in your organization.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAutoGenerateDialog(false)}>
              {autoGenerateResult ? "Close" : "Cancel"}
            </Button>
            {!autoGenerateResult && (
              <Button onClick={handleAutoGenerate} disabled={autoGenerating}>
                {autoGenerating && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
                Generate
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
